updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status bambooGit --context "$step_name"

pipelines:
  - name: build_bamboo_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: bambooGit
          integrations:
            - name: releases_temp
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_bambooGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=bamboo-artifactory-plugin
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            # Set M2_HOME
            - MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog c add releases --artifactory-url=https://releases.jfrog.io/artifactory --access-token=$int_releases_temp_token
            - ./jfrog rt mvnc
              --server-id-deploy releases --repo-deploy-releases oss-release-local --repo-deploy-snapshots oss-snapshot-local

            # Run install and publish
            - >
              env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
              ./jfrog rt mvn clean install -U -B javadoc:jar source:jar

          onComplete:
            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home